### PR TITLE
Image and other error handling

### PR DESCRIPTION
**Pull request by mcdemarco**
I was working with some slightly bad data and ran across a few error conditions to fix, plus added some general image 404 handling and a fix for the default head image when called from subdirectories (that is, people page schedules).  Also I added image handling for Grenadine's export data format, which is otherwise very close to Konopas' data format.

### CODE REVIEW

**Review by lostcarpark — APPROVED** [review]

**Comment by lostcarpark** [comment]
Useful stuff. I might tweak it so the Grenadine image link gets moved into `links` when the data is loaded, rather than handling multiple cases when rendering.
I've also discovered KonOpas accepts the image in either `links.img` or `links.photo`, so I'll probably follow suit (there are also `links.url`, `links.fb`, and `links.twitter` that I'll add in due course).

**Comment by mcdemarco** [comment]
I think it would be better to parse the data into a separate, minimal, and preferably flat structure to pass around.  Grenadine has a lot of extra stuff in the json, and KonOpas' links are just extra structure with no upside.  (It was particularly confusing that sometimes the full person data was passed to Participants.js and sometimes only a short form.)

**Comment by lostcarpark** [comment]
I think you are quite correct. I already flatten the name fields (if sent as arrays).
As you've seen, I copy fields from the People to the Program People. I've realised that it would be simpler to just replace the people in Program with references to the full People records. This would also be more memory efficient, since they would be just references to the same records rather than full copies of the fields.
I#m also finding my current method of breaking down the program into day and time slots untidy, requiring me to repeat components. I think it would be better to build a tree structure when initially loading the program, which would allow me to simplify the day and timeslot components.
I'm in the middle of a restructure that will incorporate these changes.

**Comment by lostcarpark** [comment]
I've tidied up a bit in #45.
When processing people, looks for `person.links.img`, `person.links.photo`, or `person.image_256_url`. Puts whichever finds in new `person.img` field.
Puts reference to full person record in place of partial one in `session.people`.
I think you're probably right that creating new objects so that unused fields aren't carried over would be preferable in the long run. But this at least means the the Participant and Person components only need to look at one image field.

**Pull request merged**
