### PR TITLE
Update header

### PR DESCRIPTION
**Pull request by LVerhulst4321**
Added code to the config file to allow a header image be defined. Updated header.js to display said image.
Updated the css file to display header.
Also updated the css file for the color used for person links and display of them.

### CODE REVIEW

**Comment by lostcarpark** [comment]
This looks good. Would you mind adding the new configuration settings to the ReadMe?

**Comment by LVerhulst4321** [comment]
Oh yeah! I'll add the new settings to the ReadMe.

**Comment by LVerhulst4321** [comment]
Settings have been added to the ReadMe

**Review by lostcarpark — APPROVED** [review]
This looks neat. It's definitely something I had in mind to include.

**Pull request merged**
