### PR TITLE
Expanded item - React Spring

### PR DESCRIPTION
**Pull request by lostcarpark**
Change to use React Spring for improved expanding/collapsing animation.
Removed CSS animation.
Added chevron to indicate collapsed items have expanded content.
Added rotating animation when expanding collapsing.
Added "spring" item animation.
Fixed items to always expand when in non-interactive mode or for permalink items.
Do not show chevron in non-interactive mode or for permalink items.

### CODE REVIEW

**Comment by mcdemarco** [comment]
I wasn't a big fan of the previous animation, which felt a bit choppy, but the new animation is pretty slow in my Chrome.  Is there a way to adjust the speed?

**Comment by lostcarpark** [comment]
Yes, it's using the default Spring at present. I agree it's too slow. It probably should be a setting in config. Perhaps there should be an option to disable completely.

**Comment by mcdemarco** [comment]
I think some of the delay was there before and has just become more obvious.  Maybe the expanded/collapsed tracking is slowing it down somehow.

**Comment by lostcarpark** [comment]
#84 adds a new setting for configuration of the react spring when expanding items. Can be a simple "duration", or more complex spring physics effects.

**Pull request merged**
