### PR TITLE
Performance Optimisation.

### PR DESCRIPTION
**Pull request by lostcarpark**
Changes to improve performance
- Changed date generation for date tag value
- Added loading screen
- Added "maximum items displayed" drop-down
- Additional change from using locale functions to get day name for tags, to using a static list in config, which took another half second off processing time. This has the disadvantage that it needs a list in config, but has the advantage that the day names are fully customisable.

### CODE REVIEW

**Review by LVerhulst4321 — APPROVED** [review]

**Review by LVerhulst4321 — APPROVED** [review]

**Review by LVerhulst4321 — CHANGES_REQUESTED** [review]
Something is wrong with the timezone code. I assume that your conclar.conreg.org has the change from this PR. When I tell it to display a different timezone, it is showing the wrong value. I chose to display at GMT-2:30 time and it does this:
image

I told it to use my local timezone and it did this: 
image

**Comment by lostcarpark** [comment]
Good spot!
This was caused by the change from using locale formatting functions to just formatting hour and minute. To get the timezone code, it renders one date and extracts the timezone code. I used the epoch date of 1970 for this, which seemed to work fine for most timezones, but missed that it had problems for some, possibly if they had changed their timezone some time in the last 50 years. I've changed to using the current time to get the correct timezone code. I think this might have some problems around daylight saving changeovers, so I'll continue to look at ways of improving this.

**Comment by mcdemarco** [comment]
Initial load wasn’t as snappy as Peter had hoped, but performance when navigating back to the schedule is significantly improved on the Chicon schedule.

**Review by LVerhulst4321 — APPROVED** [review]

**Comment by lostcarpark** [comment]
> Initial load wasn’t as snappy as Peter had hoped, but performance when navigating back to the schedule is significantly improved on the Chicon schedule.

Thanks for the feedback. I think there are a couple of areas we can improve things further, so I'll work on it over the next few days.

**Pull request merged**
