### PR TITLE
Uninteractive

### PR DESCRIPTION
**Pull request by mcdemarco**
This is a relatively simple, one might even say hacky, implementation of a non-interactive version of the schedule using a config value and a slimmed-down schedule filtering component.  Requested by people at Boskone who are not me.

### CODE REVIEW

**Comment by mcdemarco** [comment]
I have one up at schedule.boskone.org/still/.  (The "Invalid Date" at the bottom is caused by bad data still in Grenadine, not my changes.)

**Review by lostcarpark — COMMENTED** [review]
So do you have a separate non-interactive program guide site?

**Comment by mcdemarco** [comment]
Yes.  The regular site is still at schedule.boskone.org.  The PR doesn't permit serving both interactive and non-interactive at once, though presumably coding it that way would be very similar to what I did.  

For one thing, I didn't want to be loading the schedule twice.  Lazy loading would make that less of a concern, but the audience for this is disjoint from the app-appreciative audience so there's isn't much to gain running both at once.  They do both read the same data files (refreshed sometimes from a cron job now, which is why I'm stuck with whatever bum data is in Grenadine at the moment).  

At some point someone may copy the HTML from the static version into our main website and stop using the React version.  We shall see.

**Comment by mcdemarco** [comment]
A more likely use case would be to put up a less interactive version of the schedule before turning on full interaction, in case your schedule is preliminary or incomplete in some way.  Some more fine-grained settings for non-interactivity might be useful, too.

**Review by lostcarpark — APPROVED** [review]

**Pull request merged**
