### PR TITLE
Profile img placeholder

### PR DESCRIPTION
**Pull request by mcdemarco**
Added a setting and code for a user-specified participant image placeholder.  You can see it in action at http://test.mcdemarco.net/conclar/.

### CODE REVIEW

**Comment by lostcarpark** [comment]
Great idea.
I tend to be quite opinionated about the setting names. First off, I think it should be part of the THUMBNAILS group. Also "placeholder" for me means the text telling you what to do with a textbox. Finally, starting "USE", imply a boolian flag. So I've changed the setting to PEOPLE.THUMBNAILS.DEFAULT_IMAGE.

I also felt the logic for deciding when to show an image was getting much too complicated for the " ? : " operator, so I moved it into a function.

**Comment by lostcarpark** [comment]
I wonder should there be a default image included in the repo?

**Comment by mcdemarco** [comment]
> I wonder should there be a default image included in the repo?

It seemed complicated to actually link to the public directory from inside React code, but if you can get that working then sure.  I did not go with a particularly neutral looking image, so it would also mean finding a more typical grey silhouette with the appropriate licensing.

**Comment by lostcarpark** [comment]
Items in public get placed in the root of the site. It actually works just fine to set the DEFAULT_IMAGE to "head.png".

I rather like that image. I don't suppose it's public domain/creative commons?

**Comment by lostcarpark** [comment]
A reverse image search suggests its an Adobe image, so I expect it couldn't be included without paying someone money.

I have found a public domain image that I think will be a suitable default. It's also a SVG, making it scalable to any size while keeping the file size small.

Though part of me wants the default to be a photo of Dave McCarthy.

**Comment by mcdemarco** [comment]
I got the original of the image [here](https://publicdomainvectors.org/en/free-clipart/Human-head-color-silhouette/86437.html), which seemed public domain enough, though it comes, suspiciously, in Adobe file formats.  On the bright side, there's your vector.

My test server is running in a subdirectory so I'll check if the head still works in there.

**Pull request merged**
