### PR TITLE
Show past items filter

### PR DESCRIPTION
**Pull request by mcdemarco**
I added a filter for hiding past items, with a bit of wiggle room for what counts as "before now".  

This PR includes the bug fix from the previous one, for my convenience.  I can rebase if you need that.

### CODE REVIEW

**Review by lostcarpark — APPROVED** [review]

**Comment by lostcarpark** [comment]
Great stuff!
Thanks for finding my typo.
Hiding past items was on my to do list, so good to be able to tick that off.

**Comment by mcdemarco** [comment]
No problem!  My to do list just keeps getting longer; you can see it in my fork's issue list if you'd like.

**Comment by LVerhulst4321** [comment]
Does this use timezone of the convention or the timezone of the user to figure out if an item is in the past? I mentioned it to my program head and she said that she hopes it uses the timezone of the convention.

**Comment by mcdemarco** [comment]
> Does this use timezone of the convention or the timezone of the user to figure out if an item is in the past? I mentioned it to my program head and she said that she hopes it uses the timezone of the convention.

Javascript is bad with timezones; it only knows the user's time and there's some complicated guesswork to figure out what timezone that is and thus what time of the convention it is.  Items are in the past if they already occurred in what ConClar thinks is convention time (plus the wiggle room, so with the default settings items disappear from the short list 10 minutes after they start).  If ConClar is wrong about your timezone, it will get the past items list wrong.

If it's showing your local time correctly in the schedule, in theory it should also get the past items list right.

**Comment by LVerhulst4321** [comment]
Ok. Sounds good. Yes, timezones are complicated.

**Comment by lostcarpark** [comment]
Java has mostly good date/time functions, but is missing one major thing, which is the ability to set a datetime to be in a specific timezone (although you can specify a timezone when converting to string). Most of the workarounds seem to involve converting a datetime to a string and back to a datetime, and seeing what the difference.

Personally I'd like to see the duration used in the calculation, so maybe it disappears ten mins before the end, rather than ten mins after the start.

Anyway, I want to do some testing around this, and it really needs to be able to have convention data that you're in the middle of. To this end, I've written a PHP program that takes the program data file and reschedules everything starting at a specified start time. I've only tried it with Zambia output, but since it reads JSON, decodes it, replaces the dates, then re-encodes as JSON, it should work with any well formed JSON data that has a date property on each element.

I've checked it into my fork of Zambia:

https://github.com/lostcarpark/Zambia/blob/konOpasUpdate/konOpasUpdate.php

To run use:

`php konOpasUpdate.php YYYY-MM-DD oldfile.json newfile.json`

**Comment by lostcarpark** [comment]
Currently I'm looking at the programme in Chicago time, and items are correctly disappearing ten minutes after they start, although at present I do have to update the display manually.

**Comment by mcdemarco** [comment]
I tested manually with some data I made manually (the con for which is probably over again now) and it was fine.  My only concern is that I used a separate method to get the timezone, and it may not always agree with the one used for local time in the schedule.  I did this back when I had some sort of timing issue with using the existing functions in LocalTime, but now they could probably be combined into the same subfunction.

**Comment by lostcarpark** [comment]
That sounds fine. I just felt that having the ability to quickly update the dates in a program file allows for easily repeatable testing. Relying on manual updated files would likely lead to something getting missed.

I agree, having a single function for doing the timezone conversion would be preferable in that at least when it goes wrong, it would likely do so in a consistent manner.

**Pull request merged**
